import { Todo } from '@/lib/types';

export const mockTodos: Todo[] = [
  {
    id: 'todo-1',
    title: '파트너사 계약서 검토',
    priority: 'HIGH',
    status: 'TODO',
    assignee: '정팀장',
    deadline: '2026-03-11',
    category: '업무',
  },
  {
    id: 'todo-2',
    title: '3월 프로모션 기획안 작성',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    assignee: '김대리',
    deadline: '2026-03-12',
    category: '마케팅',
  },
  {
    id: 'todo-3',
    title: '인플루언서 미팅 일정 잡기',
    priority: 'HIGH',
    status: 'TODO',
    assignee: '이과장',
    deadline: '2026-03-14',
    category: '마케팅',
  },
  {
    id: 'todo-4',
    title: '영상 광고 3개 추가 제작',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    assignee: '박사원',
    deadline: '2026-03-14',
    category: '콘텐츠',
  },
  {
    id: 'todo-5',
    title: '월간 판매 리포트 작성',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    assignee: '김대리',
    deadline: '2026-03-05',
    category: '보고',
  },
  {
    id: 'todo-6',
    title: '경쟁사 분석 보고서',
    priority: 'MEDIUM',
    status: 'TODO',
    assignee: '박사원',
    deadline: '2026-03-15',
    category: '리서치',
  },
  {
    id: 'todo-7',
    title: '신제품 테스트 피드백 정리',
    priority: 'LOW',
    status: 'DONE',
    assignee: '이과장',
    deadline: '2026-03-08',
    category: '콘텐츠',
  },
  {
    id: 'todo-8',
    title: '블로그 콘텐츠 3건 발행',
    priority: 'LOW',
    status: 'DONE',
    assignee: '김대리',
    deadline: '2026-03-10',
    category: '콘텐츠',
  },
  {
    id: 'todo-9',
    title: '팀 회의록 정리',
    priority: 'LOW',
    status: 'TODO',
    assignee: '정팀장',
    deadline: '2026-03-11',
    category: '운영',
  },
  {
    id: 'todo-10',
    title: '예산 현황 검토',
    priority: 'LOW',
    status: 'TODO',
    assignee: '이과장',
    deadline: '2026-03-20',
    category: '보고',
  },
  {
    id: 'todo-11',
    title: 'SNS A/B 테스트 결과 분석',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    assignee: '박사원',
    deadline: '2026-03-13',
    category: '분석',
  },
];
